WARNING 2014-08-29 15:53:28 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 15:54:44 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/recommend/23 status_code:404
WARNING 2014-08-29 15:57:11 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/recommend/3 status_code:404
WARNING 2014-08-29 15:59:14 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/topic/13 status_code:404
WARNING 2014-08-29 15:59:22 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/topic/13 status_code:404
WARNING 2014-08-29 15:59:30 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/topic/13 status_code:404
WARNING 2014-08-29 16:01:17 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:01:25 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:01:32 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:03:46 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:13:55 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:15:11 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:15:11 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:15:11 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:15:11 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:15:12 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:15:27 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:15:27 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-08-29 16:18:12 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:00:29 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:00:55 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:01:15 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:03:54 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:03:54 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:03:59 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
ERROR 2014-09-01 15:04:38 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/game/detail/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./game/views.py", line 92, in detail
    user = User.objects.get(username=username)
  File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
ERROR 2014-09-01 15:04:43 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/game/detail/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./game/views.py", line 92, in detail
    user = User.objects.get(username=username)
  File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
ERROR 2014-09-01 15:04:43 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/game/detail/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./game/views.py", line 92, in detail
    user = User.objects.get(username=username)
  File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
WARNING 2014-09-01 15:04:49 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
ERROR 2014-09-01 15:04:51 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/game/detail/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./game/views.py", line 92, in detail
    user = User.objects.get(username=username)
  File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
WARNING 2014-09-01 15:07:33 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:13:50 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:14:18 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
ERROR 2014-09-01 15:16:23 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/market/hotsearch_search/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./market/hotsearch.py", line 112, in search
    }, context_instance=RequestContext(request))
  File "/usr/lib/python2.6/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python2.6/site-packages/django/template/defaulttags.py", line 942, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 276, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 331, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endblock', expected 'elif'，'else' 或 'endif'
WARNING 2014-09-01 15:16:51 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:16:53 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:16:57 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
ERROR 2014-09-01 15:33:17 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/market/hotsearch_search/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./market/hotsearch.py", line 114, in search
    }, context_instance=RequestContext(request))
  File "/usr/lib/python2.6/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/lib/python2.6/site-packages/django/utils/encoding.py", line 108, in force_text
    s = six.text_type(bytes(s), encoding, errors)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 74, in __repr__
    return repr(data)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 423, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, tuple found
ERROR 2014-09-01 15:33:19 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/market/hotsearch_search/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./market/hotsearch.py", line 114, in search
    }, context_instance=RequestContext(request))
  File "/usr/lib/python2.6/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/lib/python2.6/site-packages/django/utils/encoding.py", line 108, in force_text
    s = six.text_type(bytes(s), encoding, errors)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 74, in __repr__
    return repr(data)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 423, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, tuple found
ERROR 2014-09-01 15:33:20 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/market/hotsearch_search/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./market/hotsearch.py", line 114, in search
    }, context_instance=RequestContext(request))
  File "/usr/lib/python2.6/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/lib/python2.6/site-packages/django/utils/encoding.py", line 108, in force_text
    s = six.text_type(bytes(s), encoding, errors)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 74, in __repr__
    return repr(data)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 423, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, tuple found
ERROR 2014-09-01 15:33:41 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/market/hotsearch_search/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./market/hotsearch.py", line 114, in search
    }, context_instance=RequestContext(request))
  File "/usr/lib/python2.6/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/lib/python2.6/site-packages/django/utils/encoding.py", line 108, in force_text
    s = six.text_type(bytes(s), encoding, errors)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 74, in __repr__
    return repr(data)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 423, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, tuple found
ERROR 2014-09-01 15:34:29 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/market/hotsearch_search/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./market/hotsearch.py", line 114, in search
    }, context_instance=RequestContext(request))
  File "/usr/lib/python2.6/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/lib/python2.6/site-packages/django/utils/encoding.py", line 108, in force_text
    s = six.text_type(bytes(s), encoding, errors)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 74, in __repr__
    return repr(data)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 423, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, tuple found
ERROR 2014-09-01 15:34:30 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/market/hotsearch_search/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./market/hotsearch.py", line 114, in search
    }, context_instance=RequestContext(request))
  File "/usr/lib/python2.6/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/lib/python2.6/site-packages/django/utils/encoding.py", line 108, in force_text
    s = six.text_type(bytes(s), encoding, errors)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 74, in __repr__
    return repr(data)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 423, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, tuple found
ERROR 2014-09-01 15:34:32 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/market/hotsearch_search/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./market/hotsearch.py", line 114, in search
    }, context_instance=RequestContext(request))
  File "/usr/lib/python2.6/site-packages/django/shortcuts/__init__.py", line 29, in render_to_response
    return HttpResponse(loader.render_to_string(*args, **kwargs), **httpresponse_kwargs)
  File "/usr/lib/python2.6/site-packages/django/template/loader.py", line 169, in render_to_string
    return t.render(context_instance)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/lib/python2.6/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/usr/lib/python2.6/site-packages/django/template/debug.py", line 91, in render
    output = force_text(output)
  File "/usr/lib/python2.6/site-packages/django/utils/encoding.py", line 108, in force_text
    s = six.text_type(bytes(s), encoding, errors)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 74, in __repr__
    return repr(data)
  File "/usr/lib/python2.6/site-packages/django/db/models/base.py", line 423, in __repr__
    u = six.text_type(self)
TypeError: coercing to Unicode: need string or buffer, tuple found
ERROR 2014-09-01 15:40:01 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/game/detail/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./game/views.py", line 92, in detail
    user = User.objects.get(username=username)
  File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
WARNING 2014-09-01 15:40:38 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:40:40 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
ERROR 2014-09-01 15:40:40 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/game/detail/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./game/views.py", line 92, in detail
    user = User.objects.get(username=username)
  File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
ERROR 2014-09-01 15:41:45 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 224 Internal Server Error: /iplay_mgmt/game/detail/ status_code:500
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.6/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./game/views.py", line 92, in detail
    user = User.objects.get(username=username)
  File "/usr/lib/python2.6/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
WARNING 2014-09-01 15:42:30 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:42:31 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:42:35 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:43:39 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/market/hotsearch_search/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:43:41 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:43:41 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:43:42 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:43:42 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/detail/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:43:46 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:43:49 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:43:50 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 15:46:15 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 16:52:52 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
WARNING 2014-09-01 16:52:58 /usr/lib/python2.6/site-packages/django/core/handlers/base.py base 143 Not Found: /iplay_mgmt/game/iplay_mgmt/static/js/plugins/jqueryCookie/jquery.cookie.js status_code:404
